name: Build RK3566 Bootloader

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu build-essential make git wget python3

    - name: Clone Rockchip U-Boot
      run: |
        git clone https://github.com/christianhaitian/rk356x-uboot.git
        git clone https://github.com/rockchip-linux/rkbin
        mkdir -p ./prebuilts/gcc/linux-x86/aarch64/
        wget https://releases.linaro.org/components/toolchain/binaries/6.3-2017.05/aarch64-linux-gnu/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu.tar.xz
   
        tar Jxvf gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu.tar.xz -C ./prebuilts/gcc/linux-x86/aarch64/
        
        cp ./configs/rk3566_miyoo_defconfig u-boot/configs/
        cp ./u-boot-miyoo.dts u-boot/arch/arm/dts/rk3566-miyoo.dts
        cp ./boot.cmd ./build.sh u-boot/
        cd u-boot
        ADDR2LINE_ARM32=arm-linux-gnueabihf-addr2line
        ADDR2LINE_ARM64=aarch64-linux-gnu-addr2line
        OBJ_ARM32=arm-linux-gnueabihf-objdump
        OBJ_ARM64=aarch64-linux-gnu-objdump
        NM_ARM32=arm-linux-gnueabihf-nm
        NM_ARM64=aarch64-linux-gnu-nm
        GCC_ARM32=arm-linux-gnueabihf-
        GCC_ARM64=aarch64-linux-gnu-
        TOOLCHAIN_ARM32=../prebuilts/gcc/linux-x86/arm/gcc-linaro-6.3.1-2017.05-x86_64_arm-linux-gnueabihf/bin
        TOOLCHAIN_ARM64=../prebuilts/gcc/linux-x86/aarch64/gcc-linaro-6.3.1-2017.05-x86_64_aarch64-linux-gnu/bin
        chmod +x build.sh
        ./build.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: bootloader
        path: u-boot/bootloader.bin
