name: Build RK3566 Bootloader

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc-aarch64-linux-gnu build-essential make git wget python3

    - name: Clone Rockchip U-Boot
      run: |
        
        
        
        wget https://github.com/steward-fu/website/releases/download/trimui-brick/brick-toolchain.tar.gz
   
        tar xvf brick-toolchain.tar.gz
        mv brick /opt
        export PATH=/opt/brick/bin:$(shell echo $$PATH)
        ls
        cd miyoo
        make
        
        
       
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: miyoo_inputd
        path: miyoo/miyoo_inputd
